name: Release

on:
  push:
    branches:
      - main
      - development

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    outputs:
      version: ${{ steps.publish.outputs.version }}
      success: ${{ steps.publish.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Verify integrity
        run: npm audit signatures
      - name: Build
        run: npm run build
      - name: Link Self
        run: |-
          npm link
          npm link @ikari-engine/test-actions-one
      - name: Publish
        id: publish
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}

  test-release-success:
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ needs.publish.outputs.success == 'true' }}
    steps:
      - name: Debug
        run: |-
          echo Version is: ${{ needs.publish.outputs.version }}

  test-release-failure:
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ needs.publish.outputs.success == 'false' }}
    steps:
      - name: Debug
        run: |-
          echo Version is: ${{ needs.publish.outputs.version }}
